# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: xenial

addons:
  apt:
    sources:
    - sourceline: "deb http://archive.ubuntu.com/ubuntu/ xenial-backports universe"
    packages:
      - libhyperscan-dev