# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
dist: xenial

addons:
  apt:
    packages:
    - git
    - cmake
    - g++
    - libboost-all-dev
    - ragel

before_install:
  - ./install-hyperscan.sh
