# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hs_str_count <- function(Rstring, Rpattern) {
    .Call(`_hypeRscan_hs_str_count`, Rstring, Rpattern)
}

hs_str_detect <- function(Rstring, Rpattern) {
    .Call(`_hypeRscan_hs_str_detect`, Rstring, Rpattern)
}

hs_str_locate <- function(Rstring, Rpattern) {
    .Call(`_hypeRscan_hs_str_locate`, Rstring, Rpattern)
}

hs_verion <- function() {
    .Call(`_hypeRscan_hs_verion`)
}

hs_platform <- function() {
    .Call(`_hypeRscan_hs_platform`)
}

