# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Count the number of matches in a string.
#'
#' @param string Input character vector.
#' @param pattern Pattern to look for.
#'
#' @return An integer vector.
#' @export
#'
#' @examples
#' fruit <- c("apple", "banana", "pear", "pineapple")
#' hs_str_count(fruit, "a")
#' hs_str_count(fruit, "p")
#' hs_str_count(fruit, "e")
hs_str_count <- function(string, pattern) {
    .Call(`_hypeRscan_hs_str_count`, string, pattern)
}

#' Detect if the pattern is in a string
#' 
#' @param string Input character vector.
#' @param pattern Pattern to look for.
#'
#' @return A logical vector.
#' @export
#'
#' @examples
#' fruit <- c("apple", "banana", "pear", "pineapple")
#' hs_str_detect(fruit, "app")
#' hs_str_detect(fruit, "p")
hs_str_detect <- function(string, pattern) {
    .Call(`_hypeRscan_hs_str_detect`, string, pattern)
}

#' Locate the first instance of a pattern
#' 
#' @param string Input character vector.
#' @param pattern Pattern to look for.
#'
#' @return A integer matrix.
#' @export
#'
#' @examples
#' fruit <- c("apple", "banana", "pear", "pineapple")
#' hs_str_locate(fruit, "app")
#' hs_str_locate(fruit, "p")
hs_str_locate <- function(string, pattern) {
    .Call(`_hypeRscan_hs_str_locate`, string, pattern)
}

hs_str_locate_all <- function(string, pattern) {
    .Call(`_hypeRscan_hs_str_locate_all`, string, pattern)
}

#' Replace the first instance of a pattern
#' 
#' @param string Input character vector.
#' @param pattern Pattern to look for.
#' @param replacement String to replace pattern with.
#'
#' @return A charcter vector.
#' @export
#'
#' @examples
#' fruit <- c("apple", "banana", "pear", "pineapple")
#' hs_str_replace(fruit, "app","simi")
#' hs_str_replace(fruit, "p", "P)
hs_str_replace <- function(string, pattern, replacement) {
    .Call(`_hypeRscan_hs_str_replace`, string, pattern, replacement)
}

hs_verion <- function() {
    .Call(`_hypeRscan_hs_verion`)
}

#' Utility function to determine what CPU optimizations can be used
#'
#' @return list with cpu features and platform.
#' @export
#'
#' @examples
#' hs_platform()
hs_platform <- function() {
    .Call(`_hypeRscan_hs_platform`)
}

